// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: parrot.proto

package co.jp.r.grpc.proxy;

public interface ParrotPurchaseResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:parrot.proxy.ParrotPurchaseResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string transactionId = 1;</code>
   */
  java.lang.String getTransactionId();
  /**
   * <code>string transactionId = 1;</code>
   */
  com.google.protobuf.ByteString
      getTransactionIdBytes();

  /**
   * <code>string responseCode = 2;</code>
   */
  java.lang.String getResponseCode();
  /**
   * <code>string responseCode = 2;</code>
   */
  com.google.protobuf.ByteString
      getResponseCodeBytes();
}
