// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: parrot.proto

package co.jp.r.grpc.proxy;

public interface ParrotPurchaseRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:parrot.proxy.ParrotPurchaseRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string transactionId = 1;</code>
   */
  java.lang.String getTransactionId();
  /**
   * <code>string transactionId = 1;</code>
   */
  com.google.protobuf.ByteString
      getTransactionIdBytes();

  /**
   * <code>string requestDate = 2;</code>
   */
  java.lang.String getRequestDate();
  /**
   * <code>string requestDate = 2;</code>
   */
  com.google.protobuf.ByteString
      getRequestDateBytes();

  /**
   * <code>int32 amount = 3;</code>
   */
  int getAmount();
}
